/**
 * Local dashboard server — serves the full dashboard SPA generated by builder.ts.
 */

import express from 'express';
import { logger } from '../utils/logger.js';
import { readFromMetricsBranch, METRICS_DIR } from '../metrics/branch.js';
import { loadLatestSnapshot, loadIndex } from '../metrics/index.js';
import { buildDashboard } from './builder.js';
import type { ServeOptions } from '../types/index.js';

export async function serveDashboard(options: ServeOptions, cwd: string): Promise<void> {
  const app = express();

  // ── Main dashboard route ──────────────────────────────────────────────────
  app.get('/', (_req, res) => {
    const snapshot = loadLatestSnapshot(cwd);
    if (!snapshot) {
      res.status(404).send(noSnapshotHtml());
      return;
    }
    res.setHeader('Content-Type', 'text/html');
    res.send(buildDashboard(snapshot));
  });

  // ── API endpoints (for future use / live reload) ──────────────────────────

  app.get('/api/snapshot/latest', (_req, res) => {
    const snapshot = loadLatestSnapshot(cwd);
    if (!snapshot) {
      res.status(404).json({ error: 'No snapshots found. Run codehealth scan first.' });
      return;
    }
    res.json(snapshot);
  });

  app.get('/api/index', (_req, res) => {
    const index = loadIndex(cwd);
    if (!index) {
      res.status(404).json({ error: 'No index found.' });
      return;
    }
    res.json(index);
  });

  app.get('/api/snapshot/:timestamp', (req, res) => {
    const snapshotPath = `${METRICS_DIR}/${req.params.timestamp}.json`;
    const raw = readFromMetricsBranch(snapshotPath, cwd);
    if (!raw) {
      res.status(404).json({ error: 'Snapshot not found' });
      return;
    }
    res.json(JSON.parse(raw));
  });

  // ── Start server ──────────────────────────────────────────────────────────
  const server = app.listen(options.port, () => {
    const url = `http://localhost:${options.port}`;
    logger.success(`Dashboard running at ${url}`);

    if (options.open) {
      import('open').then(({ default: open }) => {
        open(url).catch(() => {});
      });
    }
  });

  process.on('SIGINT', () => {
    server.close(() => process.exit(0));
  });
}

function noSnapshotHtml(): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>CodeHealth</title>
<style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#f8fafc;color:#0f172a}</style>
</head><body><div style="text-align:center">
<h1 style="font-size:1.5rem;margin-bottom:8px">No snapshot found</h1>
<p style="color:#64748b">Run <code style="background:#f1f5f9;padding:2px 6px;border-radius:4px">codehealth scan</code> first, then refresh.</p>
</div></body></html>`;
}
